//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerMQ.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CmdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CmdTextField;
        
        private bool IsOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CmdId {
            get {
                return this.CmdIdField;
            }
            set {
                if ((this.CmdIdField.Equals(value) != true)) {
                    this.CmdIdField = value;
                    this.RaisePropertyChanged("CmdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CmdText {
            get {
                return this.CmdTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CmdTextField, value) != true)) {
                    this.CmdTextField = value;
                    this.RaisePropertyChanged("CmdText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsOk {
            get {
                return this.IsOkField;
            }
            set {
                if ((this.IsOkField.Equals(value) != true)) {
                    this.IsOkField = value;
                    this.RaisePropertyChanged("IsOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorDesc {
            get {
                return this.ErrorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescField, value) != true)) {
                    this.ErrorDescField = value;
                    this.RaisePropertyChanged("ErrorDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.DbServiceSoap")]
    public interface DbServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем f из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="/UploadSnapshotFile", ReplyAction="*")]
        ConsumerMQ.ServiceReference1.UploadSnapshotFileResponse UploadSnapshotFile(ConsumerMQ.ServiceReference1.UploadSnapshotFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/UploadSnapshotFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.UploadSnapshotFileResponse> UploadSnapshotFileAsync(ConsumerMQ.ServiceReference1.UploadSnapshotFileRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetCommandIdResult из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="/GetCommandId", ReplyAction="*")]
        ConsumerMQ.ServiceReference1.GetCommandIdResponse GetCommandId(ConsumerMQ.ServiceReference1.GetCommandIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/GetCommandId", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.GetCommandIdResponse> GetCommandIdAsync(ConsumerMQ.ServiceReference1.GetCommandIdRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetCommandDataResult из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="/GetCommandData", ReplyAction="*")]
        ConsumerMQ.ServiceReference1.GetCommandDataResponse GetCommandData(ConsumerMQ.ServiceReference1.GetCommandDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/GetCommandData", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.GetCommandDataResponse> GetCommandDataAsync(ConsumerMQ.ServiceReference1.GetCommandDataRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем testResult из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="/SetCommandVariablesResult", ReplyAction="*")]
        ConsumerMQ.ServiceReference1.SetCommandVariablesResultResponse SetCommandVariablesResult(ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/SetCommandVariablesResult", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.SetCommandVariablesResultResponse> SetCommandVariablesResultAsync(ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем testResult из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="/SetCommandResult", ReplyAction="*")]
        ConsumerMQ.ServiceReference1.SetCommandResultResponse SetCommandResult(ConsumerMQ.ServiceReference1.SetCommandResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/SetCommandResult", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.SetCommandResultResponse> SetCommandResultAsync(ConsumerMQ.ServiceReference1.SetCommandResultRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем testResult из пространства имен  не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="/SetCommandError", ReplyAction="*")]
        ConsumerMQ.ServiceReference1.SetCommandErrorResponse SetCommandError(ConsumerMQ.ServiceReference1.SetCommandErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="/SetCommandError", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.SetCommandErrorResponse> SetCommandErrorAsync(ConsumerMQ.ServiceReference1.SetCommandErrorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadSnapshotFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadSnapshotFile", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.UploadSnapshotFileRequestBody Body;
        
        public UploadSnapshotFileRequest() {
        }
        
        public UploadSnapshotFileRequest(ConsumerMQ.ServiceReference1.UploadSnapshotFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class UploadSnapshotFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] f;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sClientID;
        
        public UploadSnapshotFileRequestBody() {
        }
        
        public UploadSnapshotFileRequestBody(byte[] f, string fileName, string sClientID) {
            this.f = f;
            this.fileName = fileName;
            this.sClientID = sClientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadSnapshotFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadSnapshotFileResponse", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.UploadSnapshotFileResponseBody Body;
        
        public UploadSnapshotFileResponse() {
        }
        
        public UploadSnapshotFileResponse(ConsumerMQ.ServiceReference1.UploadSnapshotFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class UploadSnapshotFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadSnapshotFileResult;
        
        public UploadSnapshotFileResponseBody() {
        }
        
        public UploadSnapshotFileResponseBody(string UploadSnapshotFileResult) {
            this.UploadSnapshotFileResult = UploadSnapshotFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommandIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommandId", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.GetCommandIdRequestBody Body;
        
        public GetCommandIdRequest() {
        }
        
        public GetCommandIdRequest(ConsumerMQ.ServiceReference1.GetCommandIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetCommandIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int robotId;
        
        public GetCommandIdRequestBody() {
        }
        
        public GetCommandIdRequestBody(int robotId) {
            this.robotId = robotId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommandIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommandIdResponse", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.GetCommandIdResponseBody Body;
        
        public GetCommandIdResponse() {
        }
        
        public GetCommandIdResponse(ConsumerMQ.ServiceReference1.GetCommandIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetCommandIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumerMQ.ServiceReference1.ServiceResult GetCommandIdResult;
        
        public GetCommandIdResponseBody() {
        }
        
        public GetCommandIdResponseBody(ConsumerMQ.ServiceReference1.ServiceResult GetCommandIdResult) {
            this.GetCommandIdResult = GetCommandIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommandDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommandData", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.GetCommandDataRequestBody Body;
        
        public GetCommandDataRequest() {
        }
        
        public GetCommandDataRequest(ConsumerMQ.ServiceReference1.GetCommandDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetCommandDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cmdId;
        
        public GetCommandDataRequestBody() {
        }
        
        public GetCommandDataRequestBody(int cmdId) {
            this.cmdId = cmdId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommandDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommandDataResponse", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.GetCommandDataResponseBody Body;
        
        public GetCommandDataResponse() {
        }
        
        public GetCommandDataResponse(ConsumerMQ.ServiceReference1.GetCommandDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetCommandDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumerMQ.ServiceReference1.ServiceResult GetCommandDataResult;
        
        public GetCommandDataResponseBody() {
        }
        
        public GetCommandDataResponseBody(ConsumerMQ.ServiceReference1.ServiceResult GetCommandDataResult) {
            this.GetCommandDataResult = GetCommandDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCommandVariablesResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCommandVariablesResult", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequestBody Body;
        
        public SetCommandVariablesResultRequest() {
        }
        
        public SetCommandVariablesResultRequest(ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetCommandVariablesResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cmdId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string testResult;
        
        public SetCommandVariablesResultRequestBody() {
        }
        
        public SetCommandVariablesResultRequestBody(int cmdId, string testResult) {
            this.cmdId = cmdId;
            this.testResult = testResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCommandVariablesResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCommandVariablesResultResponse", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.SetCommandVariablesResultResponseBody Body;
        
        public SetCommandVariablesResultResponse() {
        }
        
        public SetCommandVariablesResultResponse(ConsumerMQ.ServiceReference1.SetCommandVariablesResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetCommandVariablesResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumerMQ.ServiceReference1.ServiceResult SetCommandVariablesResultResult;
        
        public SetCommandVariablesResultResponseBody() {
        }
        
        public SetCommandVariablesResultResponseBody(ConsumerMQ.ServiceReference1.ServiceResult SetCommandVariablesResultResult) {
            this.SetCommandVariablesResultResult = SetCommandVariablesResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCommandResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCommandResult", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.SetCommandResultRequestBody Body;
        
        public SetCommandResultRequest() {
        }
        
        public SetCommandResultRequest(ConsumerMQ.ServiceReference1.SetCommandResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetCommandResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cmdId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string testResult;
        
        public SetCommandResultRequestBody() {
        }
        
        public SetCommandResultRequestBody(int cmdId, string testResult) {
            this.cmdId = cmdId;
            this.testResult = testResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCommandResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCommandResultResponse", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.SetCommandResultResponseBody Body;
        
        public SetCommandResultResponse() {
        }
        
        public SetCommandResultResponse(ConsumerMQ.ServiceReference1.SetCommandResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetCommandResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumerMQ.ServiceReference1.ServiceResult SetCommandResultResult;
        
        public SetCommandResultResponseBody() {
        }
        
        public SetCommandResultResponseBody(ConsumerMQ.ServiceReference1.ServiceResult SetCommandResultResult) {
            this.SetCommandResultResult = SetCommandResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCommandErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCommandError", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.SetCommandErrorRequestBody Body;
        
        public SetCommandErrorRequest() {
        }
        
        public SetCommandErrorRequest(ConsumerMQ.ServiceReference1.SetCommandErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetCommandErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cmdId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string testResult;
        
        public SetCommandErrorRequestBody() {
        }
        
        public SetCommandErrorRequestBody(int cmdId, string testResult) {
            this.cmdId = cmdId;
            this.testResult = testResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCommandErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCommandErrorResponse", Namespace="", Order=0)]
        public ConsumerMQ.ServiceReference1.SetCommandErrorResponseBody Body;
        
        public SetCommandErrorResponse() {
        }
        
        public SetCommandErrorResponse(ConsumerMQ.ServiceReference1.SetCommandErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetCommandErrorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumerMQ.ServiceReference1.ServiceResult SetCommandErrorResult;
        
        public SetCommandErrorResponseBody() {
        }
        
        public SetCommandErrorResponseBody(ConsumerMQ.ServiceReference1.ServiceResult SetCommandErrorResult) {
            this.SetCommandErrorResult = SetCommandErrorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DbServiceSoapChannel : ConsumerMQ.ServiceReference1.DbServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbServiceSoapClient : System.ServiceModel.ClientBase<ConsumerMQ.ServiceReference1.DbServiceSoap>, ConsumerMQ.ServiceReference1.DbServiceSoap {
        
        public DbServiceSoapClient() {
        }
        
        public DbServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DbServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerMQ.ServiceReference1.UploadSnapshotFileResponse ConsumerMQ.ServiceReference1.DbServiceSoap.UploadSnapshotFile(ConsumerMQ.ServiceReference1.UploadSnapshotFileRequest request) {
            return base.Channel.UploadSnapshotFile(request);
        }
        
        public string UploadSnapshotFile(byte[] f, string fileName, string sClientID) {
            ConsumerMQ.ServiceReference1.UploadSnapshotFileRequest inValue = new ConsumerMQ.ServiceReference1.UploadSnapshotFileRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.UploadSnapshotFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            inValue.Body.sClientID = sClientID;
            ConsumerMQ.ServiceReference1.UploadSnapshotFileResponse retVal = ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).UploadSnapshotFile(inValue);
            return retVal.Body.UploadSnapshotFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.UploadSnapshotFileResponse> ConsumerMQ.ServiceReference1.DbServiceSoap.UploadSnapshotFileAsync(ConsumerMQ.ServiceReference1.UploadSnapshotFileRequest request) {
            return base.Channel.UploadSnapshotFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.UploadSnapshotFileResponse> UploadSnapshotFileAsync(byte[] f, string fileName, string sClientID) {
            ConsumerMQ.ServiceReference1.UploadSnapshotFileRequest inValue = new ConsumerMQ.ServiceReference1.UploadSnapshotFileRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.UploadSnapshotFileRequestBody();
            inValue.Body.f = f;
            inValue.Body.fileName = fileName;
            inValue.Body.sClientID = sClientID;
            return ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).UploadSnapshotFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerMQ.ServiceReference1.GetCommandIdResponse ConsumerMQ.ServiceReference1.DbServiceSoap.GetCommandId(ConsumerMQ.ServiceReference1.GetCommandIdRequest request) {
            return base.Channel.GetCommandId(request);
        }
        
        public ConsumerMQ.ServiceReference1.ServiceResult GetCommandId(int robotId) {
            ConsumerMQ.ServiceReference1.GetCommandIdRequest inValue = new ConsumerMQ.ServiceReference1.GetCommandIdRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.GetCommandIdRequestBody();
            inValue.Body.robotId = robotId;
            ConsumerMQ.ServiceReference1.GetCommandIdResponse retVal = ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).GetCommandId(inValue);
            return retVal.Body.GetCommandIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.GetCommandIdResponse> ConsumerMQ.ServiceReference1.DbServiceSoap.GetCommandIdAsync(ConsumerMQ.ServiceReference1.GetCommandIdRequest request) {
            return base.Channel.GetCommandIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.GetCommandIdResponse> GetCommandIdAsync(int robotId) {
            ConsumerMQ.ServiceReference1.GetCommandIdRequest inValue = new ConsumerMQ.ServiceReference1.GetCommandIdRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.GetCommandIdRequestBody();
            inValue.Body.robotId = robotId;
            return ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).GetCommandIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerMQ.ServiceReference1.GetCommandDataResponse ConsumerMQ.ServiceReference1.DbServiceSoap.GetCommandData(ConsumerMQ.ServiceReference1.GetCommandDataRequest request) {
            return base.Channel.GetCommandData(request);
        }
        
        public ConsumerMQ.ServiceReference1.ServiceResult GetCommandData(int cmdId) {
            ConsumerMQ.ServiceReference1.GetCommandDataRequest inValue = new ConsumerMQ.ServiceReference1.GetCommandDataRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.GetCommandDataRequestBody();
            inValue.Body.cmdId = cmdId;
            ConsumerMQ.ServiceReference1.GetCommandDataResponse retVal = ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).GetCommandData(inValue);
            return retVal.Body.GetCommandDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.GetCommandDataResponse> ConsumerMQ.ServiceReference1.DbServiceSoap.GetCommandDataAsync(ConsumerMQ.ServiceReference1.GetCommandDataRequest request) {
            return base.Channel.GetCommandDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.GetCommandDataResponse> GetCommandDataAsync(int cmdId) {
            ConsumerMQ.ServiceReference1.GetCommandDataRequest inValue = new ConsumerMQ.ServiceReference1.GetCommandDataRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.GetCommandDataRequestBody();
            inValue.Body.cmdId = cmdId;
            return ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).GetCommandDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerMQ.ServiceReference1.SetCommandVariablesResultResponse ConsumerMQ.ServiceReference1.DbServiceSoap.SetCommandVariablesResult(ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequest request) {
            return base.Channel.SetCommandVariablesResult(request);
        }
        
        public ConsumerMQ.ServiceReference1.ServiceResult SetCommandVariablesResult(int cmdId, string testResult) {
            ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequest inValue = new ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequestBody();
            inValue.Body.cmdId = cmdId;
            inValue.Body.testResult = testResult;
            ConsumerMQ.ServiceReference1.SetCommandVariablesResultResponse retVal = ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).SetCommandVariablesResult(inValue);
            return retVal.Body.SetCommandVariablesResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.SetCommandVariablesResultResponse> ConsumerMQ.ServiceReference1.DbServiceSoap.SetCommandVariablesResultAsync(ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequest request) {
            return base.Channel.SetCommandVariablesResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.SetCommandVariablesResultResponse> SetCommandVariablesResultAsync(int cmdId, string testResult) {
            ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequest inValue = new ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.SetCommandVariablesResultRequestBody();
            inValue.Body.cmdId = cmdId;
            inValue.Body.testResult = testResult;
            return ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).SetCommandVariablesResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerMQ.ServiceReference1.SetCommandResultResponse ConsumerMQ.ServiceReference1.DbServiceSoap.SetCommandResult(ConsumerMQ.ServiceReference1.SetCommandResultRequest request) {
            return base.Channel.SetCommandResult(request);
        }
        
        public ConsumerMQ.ServiceReference1.ServiceResult SetCommandResult(int cmdId, string testResult) {
            ConsumerMQ.ServiceReference1.SetCommandResultRequest inValue = new ConsumerMQ.ServiceReference1.SetCommandResultRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.SetCommandResultRequestBody();
            inValue.Body.cmdId = cmdId;
            inValue.Body.testResult = testResult;
            ConsumerMQ.ServiceReference1.SetCommandResultResponse retVal = ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).SetCommandResult(inValue);
            return retVal.Body.SetCommandResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.SetCommandResultResponse> ConsumerMQ.ServiceReference1.DbServiceSoap.SetCommandResultAsync(ConsumerMQ.ServiceReference1.SetCommandResultRequest request) {
            return base.Channel.SetCommandResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.SetCommandResultResponse> SetCommandResultAsync(int cmdId, string testResult) {
            ConsumerMQ.ServiceReference1.SetCommandResultRequest inValue = new ConsumerMQ.ServiceReference1.SetCommandResultRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.SetCommandResultRequestBody();
            inValue.Body.cmdId = cmdId;
            inValue.Body.testResult = testResult;
            return ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).SetCommandResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumerMQ.ServiceReference1.SetCommandErrorResponse ConsumerMQ.ServiceReference1.DbServiceSoap.SetCommandError(ConsumerMQ.ServiceReference1.SetCommandErrorRequest request) {
            return base.Channel.SetCommandError(request);
        }
        
        public ConsumerMQ.ServiceReference1.ServiceResult SetCommandError(int cmdId, string testResult) {
            ConsumerMQ.ServiceReference1.SetCommandErrorRequest inValue = new ConsumerMQ.ServiceReference1.SetCommandErrorRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.SetCommandErrorRequestBody();
            inValue.Body.cmdId = cmdId;
            inValue.Body.testResult = testResult;
            ConsumerMQ.ServiceReference1.SetCommandErrorResponse retVal = ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).SetCommandError(inValue);
            return retVal.Body.SetCommandErrorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.SetCommandErrorResponse> ConsumerMQ.ServiceReference1.DbServiceSoap.SetCommandErrorAsync(ConsumerMQ.ServiceReference1.SetCommandErrorRequest request) {
            return base.Channel.SetCommandErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumerMQ.ServiceReference1.SetCommandErrorResponse> SetCommandErrorAsync(int cmdId, string testResult) {
            ConsumerMQ.ServiceReference1.SetCommandErrorRequest inValue = new ConsumerMQ.ServiceReference1.SetCommandErrorRequest();
            inValue.Body = new ConsumerMQ.ServiceReference1.SetCommandErrorRequestBody();
            inValue.Body.cmdId = cmdId;
            inValue.Body.testResult = testResult;
            return ((ConsumerMQ.ServiceReference1.DbServiceSoap)(this)).SetCommandErrorAsync(inValue);
        }
    }
}
